"""
Interactive CLI for Lab 1: Agent vs Chatbot — Strict Multi-Turn Exam Planner Loop.
The agent strictly refuses to assume critical parameters, asking clarifying questions
iteratively across multiple turns until all required information is provided.
"""
import sys
import json
from src.lab1.planner_agent import ExamPlannerAgent


def print_banner(text: str):
    print("\n" + "=" * 70)
    print(f"  {text}")
    print("=" * 70)


def print_plan_summary(plan):
    print("\n📋 Current Structured Exam Plan:")
    print(f"  • Course: {plan.course_code} - {plan.course_name}")
    print(f"  • Title: {plan.exam_title}")
    print(f"  • Exam Date: {plan.exam_date} | Duration: {plan.duration_minutes} minutes | Delivery Window: {plan.delivery_window}")
    print(f"  • Total Marks: {plan.total_marks} (Passing Marks: {plan.passing_marks})")
    print(f"  • Eligibility: Min Attendance: {plan.eligibility_rules.min_attendance_percentage}%, Require Fee Clearance: {plan.eligibility_rules.require_fee_clearance}")
    print(f"  • Sections:")
    for idx, sec in enumerate(plan.sections, 1):
        print(f"     [{idx}] {sec.section_name}: {sec.question_count} Qs x {sec.marks_per_question} marks = {sec.total_section_marks} marks ({sec.section_type})")
        print(f"         Topics: {', '.join(sec.topics_covered)}")
    print(f"  • Marks Balanced: {'✅ YES' if plan.validate_marks_balance() else '❌ NO'}")


def main():
    agent = ExamPlannerAgent()
    provider_name = agent.llm.get_provider_name()
    model_name = agent.llm.get_model_name()

    print_banner(f"LAB 1: STRICT MULTI-TURN EXAM PLANNER LOOP\n  🤖 Active AI Engine: {provider_name.upper()} ({model_name})")
    print("Guiding Principle: The agent will NOT assume missing critical parameters.")
    print("It will ask clarifying questions repeatedly until all required details are provided.\n")

    # Step 1: Initial Prompt
    default_prompt = "Set up an end-semester online exam for CS301 Operating Systems"
    print(f"Example prompt: '{default_prompt}'")
    user_input = input("\nEnter your initial exam prompt: ").strip()
    if not user_input:
        user_input = default_prompt

    print(f"\n[User Prompt]: {user_input}")
    print("[Agent]: Analyzing request completeness...")

    accumulated_state = {}
    turn = 1

    # Multi-Turn Clarification Loop
    while True:
        clarification = agent.clarify_request_state(accumulated_state, user_input)
        accumulated_state = clarification.extracted_params

        if clarification.is_complete:
            print_banner("STEP 1: ALL REQUIRED PARAMETERS VERIFIED & COMPLETE")
            print(f"🧠 Verified by: {clarification.engine_used}")
            print("✅ All mandatory examination details collected without making unverified assumptions.")
            break

        print_banner(f"CLARIFICATION TURN #{turn}: MISSING INFORMATION REQUIRED")
        print(f"🧠 Generated by: {clarification.engine_used}")
        if clarification.conflict_warning:
            print(f"\n🚨 CONFLICT / CONTRADICTION DETECTED:\n   {clarification.conflict_warning}")
        print(f"\n⚠️ Status: {clarification.explanation}")
        print(f"\nParameters Collected So Far: {json.dumps(accumulated_state, indent=2)}")
        print("\nClarifying Questions for Faculty:")
        for idx, q in enumerate(clarification.clarifying_questions, 1):
            print(f"  {idx}. {q}")

        print("\nPlease provide the missing information (you can answer all or part of them):")
        user_input = input("\nYour Response: ").strip()
        if not user_input:
            print("⚠️ No input provided. The agent cannot proceed without required parameters.")
        turn += 1

    # Step 2: Propose Plan (Exact user details, no default guessing)
    print_banner("STEP 2: PROPOSING STRUCTURED EXAM PLAN")
    current_plan = agent.propose_plan(accumulated_state)
    print_plan_summary(current_plan)

    # Step 3: Revision Loop
    print_banner("STEP 3: ITERATIVE REVISION LOOP")
    while True:
        print("\nYou can now provide feedback to revise this plan (e.g., 'Change date to 2026-09-20', 'Change passing marks to 70').")
        feedback = input("Enter revision feedback (or type 'approve' / 'done' to finalize): ").strip()

        if not feedback or feedback.lower() in ["approve", "done", "exit", "quit", "q"]:
            current_plan.status = "APPROVED"
            print("\n✅ Plan finalized and signed off by Faculty!")
            print_plan_summary(current_plan)
            break

        revision = agent.revise_plan(current_plan, feedback)
        current_plan = revision.revised_plan
        print(f"\n🔄 {revision.revision_summary}")
        print_plan_summary(current_plan)

    print("\n[Lab 1 Completed Successfully] - The plan is now locked and ready for Lab 2 tools!")


if __name__ == "__main__":
    main()
